---
- name: 'Add SBT Repo'
  tags: ['sbt', 'packages']
  sudo: 'yes'
  apt_repository:
    repo="deb http://archive.canonical.com/ubuntu hardy partner"
    state=present

- name: 'Install SBT'
  tags: ['sbt', 'packages']
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    update_cache=yes
  with_items:
    - 'sbt'
