---
- name: 'Add SBT Repo'
  tags: ['sbt', 'packages']
  sudo: 'yes'
  apt_repository: >
    repo="deb http://dl.bintray.com/sbt/debian /"
    state=present

- name: 'Install SBT'
  tags: ['sbt', 'packages']
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    update_cache=yes
    force=yes
  with_items:
    - 'sbt'
